In [1]:
import os

In [2]:
import tensorflow as tf
from tensorflow.keras import models,layers,losses,metrics,callbacks 

### Data Pipline

In [3]:
file_path = "../data/train.csv"
train_path = "../data/training.csv"
test_path = "../data/testing.csv"

In [4]:
with open(file_path) as f:
    columns = f.readline()

#### split train and test data

In [5]:
'''
def split_data(file_path, train_file, test_file):
    """
    split train and test data
    for date<400, write to train data file,
    for date>=400, write to test data file.
    """
    with open(file_path) as f:
        columns = f.readline()
    
    if os.path.exists(train_file):
        os.remove(train_file)
    if os.path.exists(test_file):
        os.remove(test_file)  
    print("splitting data...")
    with open(train_file, "a") as train:
        train.write(columns)
    with open(test_file, "a") as test:
        test.write(columns)
    with open(file_path) as f:
        for line in f:
            date = line.split(",")[0]
            if not date.isdigit():
                continue
            if int(date) < 400:
                with open(train_file, "a") as train:
                    train.write(line)
            else:
                with open(test_file, "a") as test:
                    test.write(line)

split_data(file_path, train_path, test_path)

'''

splitting data...


In [6]:
with open(train_path) as t:
    print(t.readline())
    

date,weight,resp_1,resp_2,resp_3,resp_4,resp,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,feature_80,feature_81,feature_82,feature_83,feature_84,feature_85,feature_86,feature_

In [7]:
train_batches = tf.data.experimental.make_csv_dataset(
    train_path, batch_size=4,shuffle=False,
    label_name="resp")
test_batches = tf.data.experimental.make_csv_dataset(
    test_path, batch_size=4,shuffle=False,
    label_name="resp")

### build model

In [8]:
example_batch = next(iter(train_batches))[0]

In [9]:
example_batch

OrderedDict([('date',
              <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 0, 0])>),
             ('weight',
              <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.      , 16.673515,  0.      ,  0.      ], dtype=float32)>),
             ('resp_1',
              <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.00991599, -0.00282823,  0.02513386, -0.00473014], dtype=float32)>),
             ('resp_2',
              <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.01407858, -0.00322632,  0.02760739, -0.00327283], dtype=float32)>),
             ('resp_3',
              <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.00877305, -0.00731949,  0.03340572, -0.00046082], dtype=float32)>),
             ('resp_4',
              <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.00139037, -0.01111406,  0.03437974, -0.0004762 ], dtype=float32)>),
             ('feature_0',
              <tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1, -1, -1

In [ ]:
def demo(feature_column):
    feature_layer = layers.DenseFeatures(feature_column)
    print(feature_layer(example_batch).numpy())

In [ ]:
feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

In [ ]:
model = tf.keras.Sequential([
  feature_layer,
  layers.Dense(128, activation='relu'),
  layers.Dense(128, activation='relu'),
  layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'],
              run_eagerly=True)

model.fit(train_ds,
          validation_data=val_ds,
          epochs=5)

In [18]:
it = iter(train_batches)

print((next(it)[0]["date"]))

tf.Tensor([1 0 0 1], shape=(4,), dtype=int32)


In [5]:
for feature_batch, label_batch in train_batches.take(1):
    print("'resp': {}".format(label_batch))
    print("features:")
    print()
    for key, value in feature_batch.items():
        print("  {!r:20s}: {}".format(key, value))

'resp': [ 0.01519238  0.01568617  0.00022552 -0.00087303]
features:
  'date'              : [1 0 0 0]
  'weight'            : [0.47025874 0.         0.         1.4328338 ]
  'resp_1'            : [-0.00471086  0.00854328  0.00094773  0.00151781]
  'resp_2'            : [-0.00250607  0.00904607  0.00094773  0.00172566]
  'resp_3'            : [ 0.00447743  0.01842721 -0.00117745  0.00153187]
  'resp_4'            : [ 0.02102417  0.02528852 -0.00272663 -0.0013315 ]
  'feature_0'         : [1 1 1 1]
  'feature_1'         : [-1.663064    0.8587217   0.38455975  0.72780573]
  'feature_2'         : [-2.1830888  -0.42880377 -0.35049912 -0.14469783]
  'feature_3'         : [0.49478307 0.5371123  0.25024635 0.27679375]
  'feature_4'         : [0.228487   0.21077642 0.12087049 0.12522024]
  'feature_5'         : [-0.23335774  0.58595365  0.36532754  0.5616513 ]
  'feature_6'         : [-0.14445534  0.26930267  0.2196222   0.3280783 ]
  'feature_7'         : [b'-2.201458714763928' b'' b'0.3070672

In [7]:
"""
#Use the data of an eight-day window priorier of the date we are investigating as input for prediction
WINDOW_SIZE = 8

def batch_dataset(dataset):
    dataset_batched = dataset.batch(WINDOW_SIZE,drop_remainder=True)
    return dataset_batched

ds_data = tf.data.Dataset.from_tensor_slices(tf.constant(dfdiff.values,dtype = tf.float32)) \
   .window(WINDOW_SIZE,shift=1).flat_map(batch_dataset)

ds_label = tf.data.Dataset.from_tensor_slices(
    tf.constant(dfdiff.values[WINDOW_SIZE:],dtype = tf.float32))

#We put all data into one batch for better efficiency since the data volume is small.
ds_train = tf.data.Dataset.zip((ds_data,ds_label)).batch(38).cache()
"""

'\n#Use the data of an eight-day window priorier of the date we are investigating as input for prediction\nWINDOW_SIZE = 8\n\ndef batch_dataset(dataset):\n    dataset_batched = dataset.batch(WINDOW_SIZE,drop_remainder=True)\n    return dataset_batched\n\nds_data = tf.data.Dataset.from_tensor_slices(tf.constant(dfdiff.values,dtype = tf.float32))    .window(WINDOW_SIZE,shift=1).flat_map(batch_dataset)\n\nds_label = tf.data.Dataset.from_tensor_slices(\n    tf.constant(dfdiff.values[WINDOW_SIZE:],dtype = tf.float32))\n\n#We put all data into one batch for better efficiency since the data volume is small.\nds_train = tf.data.Dataset.zip((ds_data,ds_label)).batch(38).cache()\n'

### Define model

In [ ]:
class Block(layers.Layer):
    def __init__(self, **kwargs):
        super(Block, self).__init__(**kwargs)
    
    def call(self, x_input,x):
        x_out = tf.maximum((1+x)*x_input[:,-1,:],0.0)
        return x_out
    
    def get_config(self):  
        config = super(Block, self).get_config()
        return config

In [ ]:
tf.keras.backend.clear_session()
x_input = layers.Input(shape = (None,3),dtype = tf.float32)
x = layers.LSTM(3,return_sequences = True,input_shape=(None,3))(x_input)
x = layers.LSTM(3,return_sequences = True,input_shape=(None,3))(x)
x = layers.LSTM(3,return_sequences = True,input_shape=(None,3))(x)
x = layers.LSTM(3,input_shape=(None,3))(x)
x = layers.Dense(3)(x)

#We design the following block since the daily increment of confirmed, discharged and deseased cases are equal or larger than zero.
#x = tf.maximum((1+x)*x_input[:,-1,:],0.0)
x = Block()(x_input,x)
model = models.Model(inputs = [x_input],outputs = [x])
model.summary()