In [1]:
import os

In [2]:
import tensorflow as tf
from tensorflow.keras import models,layers,losses,metrics,callbacks 

## Expiriment

In [37]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [9]:
train_dev = pd.read_csv("../data/debug.csv")

In [38]:
train_dev.head()

date     weight    resp_1    resp_2    resp_3    resp_4      resp  \
0     0   0.000000  0.009916  0.014079  0.008773  0.001390  0.006270   
1     0  16.673515 -0.002828 -0.003226 -0.007319 -0.011114 -0.009792   
2     0   0.000000  0.025134  0.027607  0.033406  0.034380  0.023970   
3     0   0.000000 -0.004730 -0.003273 -0.000461 -0.000476 -0.003200   
4     0   0.138531  0.001252  0.002165 -0.001215 -0.006219 -0.002604   

   feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0          1  -1.872746  -2.191242  -0.474163  -0.323046   0.014688   
1         -1  -1.349537  -1.704709   0.068058   0.028432   0.193794   
2         -1   0.812780  -0.256156   0.806463   0.400221  -0.614188   
3         -1   1.174378   0.344640   0.066872   0.009357  -1.006373   
4          1  -3.172026  -3.093182  -0.161518  -0.128149  -0.195006   

   feature_6  feature_7  feature_8  feature_9  feature_10  feature_11  \
0  -0.002484   0.264749     0.0127  -0.989982   -1.055090    0.342371   
1   0.138212   0.264749     0.0127  -0.151877   -0.384952    0.342371   
2  -0.354800   0.264749     0.0127   5.448261    2.668029    0.342371   
3  -0.676458   0.264749     0.0127   4.508206    2.484260    0.342371   
4  -0.143780   0.264749     0.0127   2.683018    1.450991    0.342371   

   feature_12  feature_13  feature_14  feature_15  feature_16  feature_17  \
0   -0.074321   -2.667671   -2.001475   -1.703595   -2.196892     0.15616   
1   -0.074321    1.225838    0.789076    1.110580    1.102281     0.15616   
2   -0.074321    3.836342    2.183258    3.902698    3.045431     0.15616   
3   -0.074321    2.902176    1.799163    3.192700    2.848359     0.15616   
4   -0.074321    1.257761    0.632336    0.905204    0.575275     0.15616   

   feature_18  feature_19  feature_20  feature_21  feature_22  feature_23  \
0    0.033434    1.483295    1.307466    0.460831    0.173712    1.175200   
1    0.033434   -0.590600   -0.625682    0.460831    0.173712   -0.543425   
2    0.033434   -1.141082   -0.979962    0.460831    0.173712   -1.157585   
3    0.033434   -1.401637   -1.428248    0.460831    0.173712   -1.421175   
4    0.033434    2.550883    2.484082    0.460831    0.173712    2.502828   

   feature_24  feature_25  feature_26  feature_27  feature_28  feature_29  \
0    0.967805    1.608410    1.319365    0.386854    0.235952   -0.515073   
1   -0.547486   -0.706600   -0.667806    0.386854    0.235952    0.910558   
2   -0.966803   -1.430973   -1.103432    0.386854    0.235952    5.131559   
3   -1.487976   -1.756415   -1.647543    0.386854    0.235952    4.766182   
4    2.606440    2.731251    2.566561    0.386854    0.235952   -1.477905   

   feature_30  feature_31  feature_32  feature_33  feature_34  feature_35  \
0   -0.448988     0.37585    0.174779   -2.429812   -2.206423   -3.593120   
1    0.914465     0.37585    0.174779    2.137454    2.080459    2.819291   
2    4.314714     0.37585    0.174779    4.226341    3.173640    5.991513   
3    4.528353     0.37585    0.174779    3.330068    2.778468    5.603940   
4   -1.722451     0.37585    0.174779   -1.191981   -1.037629   -2.237275   

   feature_36  feature_37  feature_38  feature_39  feature_40  feature_41  \
0   -2.868358    0.112697    0.053157   -0.539956   -0.692187    3.491282   
1    2.483965   -0.086755   -0.082687    0.368431    0.469196    5.711996   
2    4.142298   -0.167927   -0.124778    0.749326    0.715824   -0.039007   
3    4.343171   -0.203161   -0.177835    0.642206    0.694692   -0.607811   
4   -1.740456    0.326904    0.221809   -0.187586   -0.272907    0.870839   

   feature_42  feature_43  feature_44  feature_45  feature_46  feature_47  \
0   -1.684889    1.337123   -0.328607    1.689207   -1.052243   -1.870885   
1   -2.215132    0.796703   -1.140081    0.716617   -0.059431   -0.198920   
2    0.186321    2.323887    0.162261    0.237987   -0.350221   -0.138033   
3    2.718151    1.656999    0.192241   -0.622152   -0.024920    0.868425   
4   

In [11]:
features = []
for item in train_dev.columns:
#     if 'feature' in item or 'weight' in item:
    if 'feature' in item:
        features.append(item)
print(features)

['feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14', 'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19', 'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24', 'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29', 'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34', 'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39', 'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44', 'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49', 'feature_50', 'feature_51', 'feature_52', 'feature_53', 'feature_54', 'feature_55', 'feature_56', 'feature_57', 'feature_58', 'feature_59', 'feature_60', 'feature_61', 'feature_62', 'feature_63', 'feature_64', 'feature_65', 'feature_66', 'feature_67', 'feature_68', 'feature_69', 'feature_70', 'feature_71', '

In [14]:
features_mean = train_dev.loc[:, features].mean()

In [18]:
train_dev.fillna(train_dev.mean(), inplace=True)

In [20]:
train_dev["stock_id"] = train_dev['feature_41'] + train_dev['feature_42'] + train_dev['feature_43'] 

In [21]:
train_dev.head()

date     weight    resp_1    resp_2    resp_3    resp_4      resp  \
0     0   0.000000  0.009916  0.014079  0.008773  0.001390  0.006270   
1     0  16.673515 -0.002828 -0.003226 -0.007319 -0.011114 -0.009792   
2     0   0.000000  0.025134  0.027607  0.033406  0.034380  0.023970   
3     0   0.000000 -0.004730 -0.003273 -0.000461 -0.000476 -0.003200   
4     0   0.138531  0.001252  0.002165 -0.001215 -0.006219 -0.002604   

   feature_0  feature_1  feature_2  ...  feature_122  feature_123  \
0          1  -1.872746  -2.191242  ...     1.168391     8.313583   
1         -1  -1.349537  -1.704709  ...    -1.178850     1.777472   
2         -1   0.812780  -0.256156  ...     6.115747     9.667908   
3         -1   1.174378   0.344640  ...     2.838853     0.499251   
4          1  -3.172026  -3.093182  ...     0.344850     4.101145   

   feature_124  feature_125  feature_126  feature_127  feature_128  \
0     1.782433    14.018213     2.653056    12.600292     2.301488   
1    -0.915458     2.831612    -1.417010     2.297459    -1.304614   
2     5.542871    11.671595     7.281757    10.060014     6.638248   
3     3.033732     1.513488     4.397532     1.266037     3.856384   
4     0.614252     6.623456     0.800129     5.233243     0.362636   

   feature_129  ts_id  stock_id  
0    11.445807      0  3.143516  
1     1.898684      1  4.293568  
2     9.427299      2  2.471201  
3     1.013469      3  3.767339  
4     3.926633      4  0.861351  

[5 rows x 139 columns]

In [48]:
X_train_dev = train_dev.loc[:, features].values

In [52]:
print('Create a easy NN model...')

HIDDEN_LAYER = [160, 160, 160]
#TARGET_NUM = 5   # 优化那5个resp

input = tf.keras.layers.Input(shape=(X_train_dev.shape[1], ))

x = tf.keras.layers.BatchNormalization()(input)
x = tf.keras.layers.Dropout(0.2)(x)
for units in HIDDEN_LAYER:
    x = tf.keras.layers.Dense(units)(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Activation(tf.keras.activations.swish)(x)  # 除了ReLU还可以试试别的，后面可以做一个多模型融合
    x = tf.keras.layers.Dropout(0.2)(x)
x = tf.keras.layers.Dense(1)(x)

output = tf.keras.layers.Activation("sigmoid")(x)

model = tf.keras.models.Model(inputs=input, outputs=output)
model.compile(
    optimizer = tf.optimizers.Adam(learning_rate=1e-3),
    metrics   = tf.keras.metrics.AUC(name="AUC"),
    loss      = tf.keras.losses.BinaryCrossentropy(label_smoothing=1e-2),
)

print('Done!')

Create a easy NN model...
Done!


In [ ]:
print('Train NN...')

history = model.fit(
    x = X_train, 
    y = y_train, 
    epochs=200, 
    batch_size=4096, 
#     validation_data=(X_valid, y_valid),
#     callbacks = EarlyStopping(monitor='roc_auc', patience=20, verbose=2, mode='max')
)
models = []
models.append(model)

print('Done!')

### Data Pipline

In [3]:
file_path = "../data/train.csv"
train_path = "../data/training.csv"
test_path = "../data/testing.csv"

In [4]:
with open(file_path) as f:
    columns = f.readline()

#### split train and test data

In [5]:
'''
def split_data(file_path, train_file, test_file):
    """
    split train and test data
    for date<400, write to train data file,
    for date>=400, write to test data file.
    """
    with open(file_path) as f:
        columns = f.readline()
    
    if os.path.exists(train_file):
        os.remove(train_file)
    if os.path.exists(test_file):
        os.remove(test_file)  
    print("splitting data...")
    with open(train_file, "a") as train:
        train.write(columns)
    with open(test_file, "a") as test:
        test.write(columns)
    with open(file_path) as f:
        for line in f:
            date = line.split(",")[0]
            if not date.isdigit():
                continue
            if int(date) < 400:
                with open(train_file, "a") as train:
                    train.write(line)
            else:
                with open(test_file, "a") as test:
                    test.write(line)

split_data(file_path, train_path, test_path)

'''

splitting data...


In [6]:
with open(train_path) as t:
    print(t.readline())
    

date,weight,resp_1,resp_2,resp_3,resp_4,resp,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,feature_80,feature_81,feature_82,feature_83,feature_84,feature_85,feature_86,feature_

In [4]:
train_batches = tf.data.experimental.make_csv_dataset(
    train_path, batch_size=4,shuffle=False,
    label_name="resp")
test_batches = tf.data.experimental.make_csv_dataset(
    test_path, batch_size=4,shuffle=False,
    label_name="resp")

### build model

In [8]:
example_batch = next(iter(train_batches))[0]

In [9]:
example_batch

OrderedDict([('date',
              <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 0, 0])>),
             ('weight',
              <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.      , 16.673515,  0.      ,  0.      ], dtype=float32)>),
             ('resp_1',
              <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.00991599, -0.00282823,  0.02513386, -0.00473014], dtype=float32)>),
             ('resp_2',
              <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.01407858, -0.00322632,  0.02760739, -0.00327283], dtype=float32)>),
             ('resp_3',
              <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.00877305, -0.00731949,  0.03340572, -0.00046082], dtype=float32)>),
             ('resp_4',
              <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.00139037, -0.01111406,  0.03437974, -0.0004762 ], dtype=float32)>),
             ('feature_0',
              <tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1, -1, -1

In [ ]:
def demo(feature_column):
    feature_layer = layers.DenseFeatures(feature_column)
    print(feature_layer(example_batch).numpy())

In [ ]:
feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

In [ ]:
model = tf.keras.Sequential([
  feature_layer,
  layers.Dense(128, activation='relu'),
  layers.Dense(128, activation='relu'),
  layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'],
              run_eagerly=True)

model.fit(train_ds,
          validation_data=val_ds,
          epochs=5)

In [18]:
it = iter(train_batches)

print((next(it)[0]["date"]))

tf.Tensor([1 0 0 1], shape=(4,), dtype=int32)


In [5]:
for feature_batch, label_batch in train_batches.take(1):
    print("'resp': {}".format(label_batch))
    print("features:")
    print()
    for key, value in feature_batch.items():
        print("  {!r:20s}: {}".format(key, value))

'resp': [ 0.01519238  0.01568617  0.00022552 -0.00087303]
features:
  'date'              : [1 0 0 0]
  'weight'            : [0.47025874 0.         0.         1.4328338 ]
  'resp_1'            : [-0.00471086  0.00854328  0.00094773  0.00151781]
  'resp_2'            : [-0.00250607  0.00904607  0.00094773  0.00172566]
  'resp_3'            : [ 0.00447743  0.01842721 -0.00117745  0.00153187]
  'resp_4'            : [ 0.02102417  0.02528852 -0.00272663 -0.0013315 ]
  'feature_0'         : [1 1 1 1]
  'feature_1'         : [-1.663064    0.8587217   0.38455975  0.72780573]
  'feature_2'         : [-2.1830888  -0.42880377 -0.35049912 -0.14469783]
  'feature_3'         : [0.49478307 0.5371123  0.25024635 0.27679375]
  'feature_4'         : [0.228487   0.21077642 0.12087049 0.12522024]
  'feature_5'         : [-0.23335774  0.58595365  0.36532754  0.5616513 ]
  'feature_6'         : [-0.14445534  0.26930267  0.2196222   0.3280783 ]
  'feature_7'         : [b'-2.201458714763928' b'' b'0.3070672

In [7]:
"""
#Use the data of an eight-day window priorier of the date we are investigating as input for prediction
WINDOW_SIZE = 8

def batch_dataset(dataset):
    dataset_batched = dataset.batch(WINDOW_SIZE,drop_remainder=True)
    return dataset_batched

ds_data = tf.data.Dataset.from_tensor_slices(tf.constant(dfdiff.values,dtype = tf.float32)) \
   .window(WINDOW_SIZE,shift=1).flat_map(batch_dataset)

ds_label = tf.data.Dataset.from_tensor_slices(
    tf.constant(dfdiff.values[WINDOW_SIZE:],dtype = tf.float32))

#We put all data into one batch for better efficiency since the data volume is small.
ds_train = tf.data.Dataset.zip((ds_data,ds_label)).batch(38).cache()
"""

'\n#Use the data of an eight-day window priorier of the date we are investigating as input for prediction\nWINDOW_SIZE = 8\n\ndef batch_dataset(dataset):\n    dataset_batched = dataset.batch(WINDOW_SIZE,drop_remainder=True)\n    return dataset_batched\n\nds_data = tf.data.Dataset.from_tensor_slices(tf.constant(dfdiff.values,dtype = tf.float32))    .window(WINDOW_SIZE,shift=1).flat_map(batch_dataset)\n\nds_label = tf.data.Dataset.from_tensor_slices(\n    tf.constant(dfdiff.values[WINDOW_SIZE:],dtype = tf.float32))\n\n#We put all data into one batch for better efficiency since the data volume is small.\nds_train = tf.data.Dataset.zip((ds_data,ds_label)).batch(38).cache()\n'

### Define model

In [ ]:
class Block(layers.Layer):
    def __init__(self, **kwargs):
        super(Block, self).__init__(**kwargs)
    
    def call(self, x_input,x):
        x_out = tf.maximum((1+x)*x_input[:,-1,:],0.0)
        return x_out
    
    def get_config(self):  
        config = super(Block, self).get_config()
        return config

In [ ]:
tf.keras.backend.clear_session()
x_input = layers.Input(shape = (None,3),dtype = tf.float32)
x = layers.LSTM(3,return_sequences = True,input_shape=(None,3))(x_input)
x = layers.LSTM(3,return_sequences = True,input_shape=(None,3))(x)
x = layers.LSTM(3,return_sequences = True,input_shape=(None,3))(x)
x = layers.LSTM(3,input_shape=(None,3))(x)
x = layers.Dense(3)(x)

#We design the following block since the daily increment of confirmed, discharged and deseased cases are equal or larger than zero.
#x = tf.maximum((1+x)*x_input[:,-1,:],0.0)
x = Block()(x_input,x)
model = models.Model(inputs = [x_input],outputs = [x])
model.summary()